### ISSUE TITLE
Tests aren't testing anything.

### ISSUE THREAD

**Issue by johnbonesnj** [codeship-tutorials/codefish-node#3]
The 2 specs provided don't function properly, if you run jasmine-node with the 
"--captureExceptions" flag you will see:

```
..

Finished in 0.039 seconds
2 tests, 0 assertions, 0 failures, 0 skipped


TypeError: Object [ A ] has no method 'text'
    at /Users/john/Projects/Javascript/Node/codefish-node/spec/frontpage_spec.js:15:65
    at _fulfilled (/Users/john/Projects/Javascript/Node/codefish-node/node_modules/zombie/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/john/Projects/Javascript/Node/codefish-node/node_modules/zombie/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/john/Projects/Javascript/Node/codefish-node/node_modules/zombie/node_modules/q/q.js:759:13)
    at /Users/john/Projects/Javascript/Node/codefish-node/node_modules/zombie/node_modules/q/q.js:573:44
    at flush (/Users/john/Projects/Javascript/Node/codefish-node/node_modules/zombie/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:415:13)
```

**Comment by clemenshelm** [comment]
Thanks for reporting this, I just fixed it in 1f4b36b03f3597c542d2d07c88d7b3272a4064c8.
